### ISSUE TITLE
Specific Domain Name?

### ISSUE THREAD

**Issue by baileythegreen** [baileythegreen/Chronic-Learning#8]
Does `domainName = projectName = twitterHandle` mean things are easier for someone to find?
### Current values
domainName == https://baileythegreen.github.io/Chronic-Learning/      (non-functional, at the moment)
projectName == Chronic Learning
twitterHandle == @ChronicLearning

### Contact:
Email address for contact is: baileythestudent@gmail.com

***
### Possible domain names:
www.chroniclearning.???
www.theperpetualstudent.???

**Comment by thismatters** [comment]
I think that having a consistent name across social media which aligns with the name of the service is pretty important for building a brand.

**Comment by baileythegreen** [comment]
@thismatters I do not disagree. Which is why I registered chroniclearning.org a week ago. (Also, because registering domains turned out to not be the expensive thing I thought it was, I got chroniclearning.net and chroniclearning.com, too, and pointed to the .org.)

You can try them. They're linked to this repository (which doesn't have quite everything it needs for a dummy site, yet), so they'll give a GitHub 404 page at the moment, but I'm hoping this will change in the next ~20 minutes. I can at least serve the site locally now.

**Comment by baileythegreen** [comment]
It works now! I had added the necessary files to the wrong branch....

**Comment by thismatters** [comment]
Well done!
